repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: mixed-line-ending
        args: ["--fix=lf"]

-   repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
    -   id: black

- repo: https://github.com/floatingpurr/sync_with_poetry
  rev: "" # the revision or tag to clone at
  hooks:
    - id: sync_with_poetry
      args: [] # optional args

#- repo: https://github.com/elliottower/cathedral-rl
#  rev: 'v1.0.0'
#  hooks:
#  -   id: poetry-check
#  -   id: poetry-lock
#  -   id: poetry-export
#      args: ["-f", "requirements.txt", "-o", "requirements.txt"]
