repos:
  - repo: https://github.com/python/black
    rev: 22.8.0
    hooks:
      - id: black
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.1
    hooks:
      - id: codespell
        args:
          - --skip=*.css,*.js,*.map,*.scss,*svg
          - --ignore-words-list=magent
  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        args:
          - --per-file-ignores=*/__init__.py:F401 */cathedral_v0.py:F401
          - --extend-ignore=E203
          - --max-complexity=205
          - --max-line-length=300
          - --show-source
          - --statistics
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.38.0
    hooks:
      - id: pyupgrade
        args: ["--py38-plus", "--keep-runtime-typing"]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: mixed-line-ending
        args: ["--fix=lf"]

  # TODO: fix pyright errors (add static typing)
#  - repo: local
#    hooks:
#      - id: pyright
#        name: pyright
#        entry: pyright
#        language: node
#        pass_filenames: false
#        types: [python]
#        additional_dependencies: ["pyright"]

  - repo: https://github.com/floatingpurr/sync_with_poetry
    rev: "" # the revision or tag to clone at
    hooks:
      - id: sync_with_poetry
        args: [--all] # optional args

  - repo: https://github.com/python-poetry/poetry
    rev: ''  # add version here
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-export
        args: [ "-f", "requirements.txt", "-o", "requirements.txt" ]
ci:
    autofix_commit_msg: |
        [pre-commit.ci] auto fixes from pre-commit.com hooks

        for more information, see https://pre-commit.ci
    autofix_prs: true
    autoupdate_branch: ''
    autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
    autoupdate_schedule: monthly
    skip: []
    submodules: false
